### ISSUE TITLE
Clear databases does not work

### ISSUE THREAD

**Issue by holo-lb** [holo-lb/BunyipsChatapp#35]
Firestore rules are set properly, however there is something wrong with the code that prohibits deleting a collection. This could be due to the blocking nature of the code that was implemented.

Resources to assist:
https://github.com/firebase/snippets-node/blob/e5f6214059bdbc63f94ba6600f7f84e96325548d/firestore/main/index.js#L889-L921

**Comment by mdyusufkhan101** [comment]
You should try catching the errors in after you delete your batch like this --

`query.get().then(function(querySnapshot) {
    querySnapshot.forEach(function(doc) {
        batch.delete(doc.ref);
    });
    // Commit the batch
    return batch.commit();
}).then(function() {
    console.log("Documents deleted successfully.");
}).catch(function(error) {
    console.error("Error deleting documents: ", error);
});`

This way you can get the error and then it will be much easier for you to understand what is wrong.  If you are deleting more than 500 docs then batch function won't work, maybe that is why you are getting the error.
Good luck!!
